# Generated by Django 5.1.4 on 2025-04-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Место жительства')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, unique=True, verbose_name='Номер паспорта')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('passport_issued_by', models.CharField(max_length=100, verbose_name='Кем выдан паспорт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Номер счета')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро'), ('CNY', 'Юани')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('account_type', models.CharField(choices=[('current', 'Текущий'), ('settlement', 'Расчетный'), ('credit', 'Кредитный'), ('deposit', 'Депозитный'), ('budget', 'Бюджетный (соц. выплаты)'), ('standard', 'Стандартный расчетный'), ('active', 'Активный'), ('passive', 'Пассивный')], max_length=30, verbose_name='Тип счета')),
                ('is_legal_entity', models.BooleanField(default=False, verbose_name='Юридическое лицо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='myapp.client')),
            ],
        ),
    ]
