# Generated by Django 5.1.4 on 2025-04-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(max_length=20, unique=True, verbose_name='БИК')),
                ('correspondent_account', models.CharField(max_length=50, verbose_name='Корреспондентский счёт')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=20, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=20, verbose_name='ОКПО')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('swift', models.CharField(blank=True, max_length=20, verbose_name='SWIFT‑код')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Банк‑получатель')),
                ('address', models.CharField(max_length=255, verbose_name='Юридический адрес банка')),
                ('post_address', models.CharField(blank=True, max_length=255, verbose_name='Почтовый адрес банка')),
            ],
            options={
                'verbose_name': 'Реквизиты банка',
                'verbose_name_plural': 'Реквизиты банков',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='DepositRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название счёта')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Номер счёта')),
                ('product_type', models.CharField(max_length=100, verbose_name='Тип депозита (продукт)')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма на счёте')),
                ('nominal_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Номинальная ставка')),
                ('current_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Текущая ставка')),
                ('interest_payout', models.CharField(max_length=100, verbose_name='Проценты выплачиваются')),
                ('status', models.CharField(max_length=50, verbose_name='Текущее состояние')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Максимальная сумма')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Минимальная сумма')),
                ('open_date', models.DateField(verbose_name='Дата открытия')),
                ('next_accrual_date', models.DateField(verbose_name='Дата следующего начисления')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Закрытие счёта')),
                ('visibility', models.CharField(max_length=100, verbose_name='Видимость счёта')),
            ],
            options={
                'verbose_name': 'Реквизиты депозита клиента',
                'verbose_name_plural': 'Реквизиты депозитов клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientAccountRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Номер счёта')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_accounts', to='myapp.bankdetail', verbose_name='Банк')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_requisites', to='myapp.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Реквизиты счёта клиента',
                'verbose_name_plural': 'Реквизиты счёта клиентов',
            },
        ),
        migrations.CreateModel(
            name='CardRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Номер карты')),
                ('card_type', models.CharField(max_length=50, verbose_name='Тип карты')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Имя владельца')),
                ('expiry_date', models.DateField(verbose_name='Срок действия')),
                ('security_code', models.CharField(max_length=10, verbose_name='Код безопасности')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_requisite', to='myapp.clientaccountrequisite', verbose_name='Реквизиты счёта')),
            ],
            options={
                'verbose_name': 'Реквизиты карты',
                'verbose_name_plural': 'Реквизиты карт',
            },
        ),
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='myapp.clientaccountrequisite', verbose_name='Реквизиты счёта клиента')),
                ('card_requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='myapp.cardrequisite', verbose_name='Реквизиты карты')),
            ],
            options={
                'verbose_name': 'Клиентская карта',
                'verbose_name_plural': 'Клиентские карты',
            },
        ),
        migrations.CreateModel(
            name='ClientDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='myapp.clientaccountrequisite', verbose_name='Реквизиты счёта клиента')),
                ('deposit_requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='myapp.depositrequisite', verbose_name='Реквизиты депозита клиента')),
            ],
            options={
                'verbose_name': 'Клиентский депозит',
                'verbose_name_plural': 'Клиентские депозиты',
            },
        ),
        migrations.CreateModel(
            name='PassportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('registration_address', models.CharField(max_length=255, verbose_name='Адрес регистрации')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('series', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('issued_date', models.DateField(verbose_name='Когда выдан')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='myapp.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Реквизиты паспорта',
                'verbose_name_plural': 'Реквизиты паспортов',
            },
        ),
    ]
